version: "3.8"

services:
  postgres_db:
    container_name: db_spring_menu
    image: postgres:13-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
      - POSTGRES_DB=menu-db
    networks:
      - my_network
    volumes:
      - dev_postgres_data:/var/lib/postgresql/data/
    restart: always
  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    networks:
       - my_network
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
    depends_on:
      - postgres_db

networks:
  my_network:
    name: my_network

volumes:
  dev_postgres_data: